package secure;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Nazibur
 */
public class login extends javax.swing.JFrame {
   
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setTitle("School Management");
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallpnl = new javax.swing.JPanel();
        passlbl = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        userlbl = new javax.swing.JLabel();
        extbtn = new javax.swing.JButton();
        teacherlogin = new javax.swing.JButton();
        passtxt = new javax.swing.JPasswordField();
        adminlogin = new javax.swing.JButton();
        studentlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginmsglbl = new javax.swing.JLabel();
        walllbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wallpnl.setLayout(null);

        passlbl.setBackground(new java.awt.Color(152, 200, 116));
        passlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/passsss_1.png"))); // NOI18N
        passlbl.setText("Password");
        wallpnl.add(passlbl);
        passlbl.setBounds(110, 360, 100, 40);

        usertxt.setBackground(new java.awt.Color(255, 255, 51));
        usertxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        wallpnl.add(usertxt);
        usertxt.setBounds(220, 320, 200, 30);

        userlbl.setBackground(new java.awt.Color(152, 200, 116));
        userlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/ussssssssss.png"))); // NOI18N
        userlbl.setText("User Name");
        wallpnl.add(userlbl);
        userlbl.setBounds(110, 320, 110, 40);

        extbtn.setBackground(new java.awt.Color(196, 87, 18));
        extbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        extbtn.setText("EXIT");
        extbtn.setBorder(null);
        extbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extbtnActionPerformed(evt);
            }
        });
        wallpnl.add(extbtn);
        extbtn.setBounds(700, 460, 100, 40);

        teacherlogin.setBackground(new java.awt.Color(220, 146, 37));
        teacherlogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        teacherlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/ft.png"))); // NOI18N
        teacherlogin.setText("Teacher");
        teacherlogin.setBorder(null);
        teacherlogin.setPreferredSize(new java.awt.Dimension(85, 35));
        teacherlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherloginActionPerformed(evt);
            }
        });
        wallpnl.add(teacherlogin);
        teacherlogin.setBounds(390, 400, 100, 40);

        passtxt.setBackground(new java.awt.Color(255, 255, 51));
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        wallpnl.add(passtxt);
        passtxt.setBounds(220, 360, 200, 30);

        adminlogin.setBackground(new java.awt.Color(220, 146, 37));
        adminlogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        adminlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/Admin-icon.png"))); // NOI18N
        adminlogin.setText("Admin");
        adminlogin.setBorder(null);
        adminlogin.setPreferredSize(new java.awt.Dimension(85, 35));
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        wallpnl.add(adminlogin);
        adminlogin.setBounds(290, 400, 90, 40);

        studentlogin.setBackground(new java.awt.Color(220, 146, 37));
        studentlogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        studentlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/st.png"))); // NOI18N
        studentlogin.setText("Student");
        studentlogin.setBorder(null);
        studentlogin.setPreferredSize(new java.awt.Dimension(85, 35));
        studentlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentloginActionPerformed(evt);
            }
        });
        wallpnl.add(studentlogin);
        studentlogin.setBounds(500, 400, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/login.png"))); // NOI18N
        wallpnl.add(jLabel1);
        jLabel1.setBounds(230, 398, 50, 50);

        loginmsglbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginmsglbl.setText("Login as :");
        wallpnl.add(loginmsglbl);
        loginmsglbl.setBounds(120, 410, 100, 30);

        walllbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/800px_COLOURBOX5665997.jpg"))); // NOI18N
        walllbl.setPreferredSize(new java.awt.Dimension(800, 500));
        wallpnl.add(walllbl);
        walllbl.setBounds(0, 0, 800, 500);

        getContentPane().add(wallpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void teacherloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherloginActionPerformed
        // TODO add your handling code here:
       conn = MySqlConnect1.ConnectDB();
        String Sql = "Select * from teacher where username = ? and password = ?";
        try{
        
            pst = conn.prepareStatement(Sql);
            pst.setString(1,usertxt.getText());
            pst.setString(2,passtxt.getText());
            rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null, "Teacher Succesfully Logged in");
            studentsupdate su = new studentsupdate();
            su.setVisible(true);
            
            }
            else{
            
                JOptionPane.showMessageDialog(null,"Invalid entry","Access Denied",JOptionPane.ERROR_MESSAGE);
            
            }
        }catch(Exception e){
        
        
            JOptionPane.showMessageDialog(null, e);
        }

        
    }//GEN-LAST:event_teacherloginActionPerformed

    private void extbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_extbtnActionPerformed

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect.ConnectDB();
        String Sql = "Select * from admin where username = ? and password = ?";
        try{
        
            pst = conn.prepareStatement(Sql);
            pst.setString(1,usertxt.getText());
            pst.setString(2,passtxt.getText());
            rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null, "Admin Succesfully Logged in");
            studentinfo si = new studentinfo();
            si.setVisible(true);
            
            }
            else{
            
                JOptionPane.showMessageDialog(null,"Invalid entry","Access Denied",JOptionPane.ERROR_MESSAGE);
            
            }
        }catch(Exception e){
        
        
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_adminloginActionPerformed

    private void studentloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentloginActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect2.ConnectDB();
        String Sql = "Select * from student where username = ? and password = ?";
        try{
        
            pst = conn.prepareStatement(Sql);
            pst.setString(1,usertxt.getText());
            pst.setString(2,passtxt.getText());
            rs = pst.executeQuery();
            if(rs.next()){
            JOptionPane.showMessageDialog(null, "Student Succesfully Logged in");
            studentview sv = new studentview();
            sv.setVisible(true);
            
            }
            else{
            
                JOptionPane.showMessageDialog(null,"Invalid entry","Access Denied",JOptionPane.ERROR_MESSAGE);
            
            }
        }catch(Exception e){
        
        
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_studentloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }     
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminlogin;
    private javax.swing.JButton extbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginmsglbl;
    private javax.swing.JLabel passlbl;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JButton studentlogin;
    private javax.swing.JButton teacherlogin;
    private javax.swing.JLabel userlbl;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel walllbl;
    private javax.swing.JPanel wallpnl;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("dgre.png")));
         //To change body of generated methods, choose Tools | Templates.
    }
}
