/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nazibur
 */
public class studentsupdate extends javax.swing.JFrame {

    /**
     * Creates new form studentsupdate
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public studentsupdate() {
        initComponents();
        setIcon();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fefld = new javax.swing.JTextField();
        iddfld = new javax.swing.JTextField();
        fifld = new javax.swing.JTextField();
        refld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable25 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        insertbtn = new javax.swing.JButton();
        clrbtn = new javax.swing.JButton();
        dlbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        fefld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(fefld);
        fefld.setBounds(540, 120, 130, 30);

        iddfld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iddfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddfldActionPerformed(evt);
            }
        });
        jPanel1.add(iddfld);
        iddfld.setBounds(540, 90, 130, 30);

        fifld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(fifld);
        fifld.setBounds(540, 150, 130, 30);

        refld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(refld);
        refld.setBounds(540, 180, 130, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/up.png"))); // NOI18N
        jLabel2.setText("Students Update");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 380, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Result :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 190, 60, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fine :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(430, 160, 40, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fees :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 130, 40, 15);

        jTable25.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable25);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(380, 290, 420, 160);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/teacher.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 50, 480, 580);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Students ID : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 90, 110, 30);

        closebtn.setBackground(new java.awt.Color(255, 204, 0));
        closebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        closebtn.setText("CLOSE");
        closebtn.setPreferredSize(new java.awt.Dimension(41, 23));
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn);
        closebtn.setBounds(690, 450, 100, 40);

        insertbtn.setBackground(new java.awt.Color(218, 208, 191));
        insertbtn.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });
        jPanel1.add(insertbtn);
        insertbtn.setBounds(490, 250, 80, 30);

        clrbtn.setBackground(new java.awt.Color(218, 208, 191));
        clrbtn.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        clrbtn.setText("Clear");
        clrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clrbtn);
        clrbtn.setBounds(580, 250, 80, 30);

        dlbtn.setBackground(new java.awt.Color(218, 208, 191));
        dlbtn.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        dlbtn.setText("Delete by ID");
        dlbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlbtnActionPerformed(evt);
            }
        });
        jPanel1.add(dlbtn);
        dlbtn.setBounds(670, 250, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/44.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iddfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddfldActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        // TODO add your handling code here:
        conn = MySqlConnect6.ConnectDB();
        try{
            String sql = "INSERT INTO studentup"
                    +"(ID, Fees, Fine, Result)"
                    +"VALUES (?,?,?,?)";
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb","root","");
            pst = conn.prepareStatement(sql);
            pst.setString(1,iddfld.getText());
            pst.setString(2,fefld.getText());
             pst.setString(3,fifld.getText());
              pst.setString(4,refld.getText());
              
              
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null, "Inserted successfully");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        showTableData();
    }//GEN-LAST:event_insertbtnActionPerformed

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed
        // TODO add your handling code here:
          iddfld.setText("");
          fefld.setText("");
          fifld.setText("");
          refld.setText("");
          showTableData();
    }//GEN-LAST:event_clrbtnActionPerformed

    private void dlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlbtnActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM studentup WHERE ID =?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb","root","");
            pst = conn.prepareStatement(sql);
            pst.setString(1,iddfld.getText());
            pst.executeUpdate();
              JOptionPane.showMessageDialog(null, "Deleted  Successfully");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        showTableData();
    }//GEN-LAST:event_dlbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentsupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentsupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentsupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentsupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentsupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JButton clrbtn;
    private javax.swing.JButton dlbtn;
    private javax.swing.JTextField fefld;
    private javax.swing.JTextField fifld;
    private javax.swing.JTextField iddfld;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable25;
    private javax.swing.JTextField refld;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("dgre.png")));//To change body of generated methods, choose Tools | Templates.
    }

    private void showTableData() {
            try{
         conn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb","root","");
         String sql = "SELECT ID, Fees, Fine, Result FROM studentup";
         pst = conn.prepareStatement(sql);
         rs=pst.executeQuery();
         jTable25.setModel(DbUtils.resultSetToTableModel(rs));
 }
     catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
         
     }
    }
}
