/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secure;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Nazibur
 */
public class studentinfo extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form studentinfo
     */
    public studentinfo() {
        initComponents();
        setTitle("School Management");
        setIcon();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namefld = new javax.swing.JTextField();
        agefld = new javax.swing.JTextField();
        ffld = new javax.swing.JTextField();
        mfld = new javax.swing.JTextField();
        cfld = new javax.swing.JTextField();
        afld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insertbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable21 = new javax.swing.JTable();
        closebtn = new javax.swing.JButton();
        clrbtn = new javax.swing.JButton();
        idlbl = new javax.swing.JLabel();
        idfld = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 250));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Father's Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Mother's Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Address :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Contact :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Age :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 20));

        namefld.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(namefld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 270, -1));

        agefld.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(agefld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, -1));

        ffld.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(ffld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 270, -1));

        mfld.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfldActionPerformed(evt);
            }
        });
        jPanel1.add(mfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 270, -1));

        cfld.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(cfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 110, -1));

        afld.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        afld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        afld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afldActionPerformed(evt);
            }
        });
        jPanel1.add(afld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 270, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/data.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 120, -1));

        insertbtn.setBackground(new java.awt.Color(106, 193, 168));
        insertbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });
        jPanel1.add(insertbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 80, 40));

        delbtn.setBackground(new java.awt.Color(106, 193, 168));
        delbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delbtn.setText("Delete by ID");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });
        jPanel1.add(delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 160, 40));

        jTable21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable21);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 260, 800, 200));

        closebtn.setBackground(new java.awt.Color(255, 204, 0));
        closebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        closebtn.setText("CLOSE");
        closebtn.setPreferredSize(new java.awt.Dimension(41, 23));
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 100, 40));

        clrbtn.setBackground(new java.awt.Color(106, 193, 168));
        clrbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clrbtn.setText("Clear");
        clrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbtnActionPerformed(evt);
            }
        });
        jPanel1.add(clrbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 80, 40));

        idlbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idlbl.setText("ID :");
        jPanel1.add(idlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        idfld.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(idfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 270, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secure/lollllllll.png"))); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfldActionPerformed

    private void afldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afldActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        // TODO add your handling code here:
    
        conn = MySqlConnect5.ConnectDB();
        try{
            String sql = "INSERT INTO studentinfo"
                    +"(ID, Name, FathersName, MothersName, Age, Address, Contact)"
                    +"VALUES (?,?,?,?,?,?,?)";
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb","root","");
            pst = conn.prepareStatement(sql);
            pst.setString(1,idfld.getText());
            pst.setString(2,namefld.getText());
             pst.setString(3,ffld.getText());
              pst.setString(4,mfld.getText());
              pst.setString(5,agefld.getText());
             pst.setString(6,afld.getText());
              pst.setString(7,cfld.getText());
              
              
              pst.executeUpdate();
              JOptionPane.showMessageDialog(null, "Inserted successfully");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
 
        showTableData();
    }//GEN-LAST:event_insertbtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
        
          try{
            String sql = "DELETE FROM studentinfo WHERE ID =?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb","root","");
            pst = conn.prepareStatement(sql);
            pst.setString(1,idfld.getText());
            pst.executeUpdate();
              JOptionPane.showMessageDialog(null, "Deleted  Successfully");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        showTableData();
    }//GEN-LAST:event_delbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed
        // TODO add your handling code here:
        idfld.setText("");
        namefld.setText("");
        agefld.setText("");
        ffld.setText("");
        mfld.setText("");
        cfld.setText("");
        afld.setText("");
        
    }//GEN-LAST:event_clrbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField afld;
    private javax.swing.JTextField agefld;
    private javax.swing.JTextField cfld;
    private javax.swing.JButton closebtn;
    private javax.swing.JButton clrbtn;
    private javax.swing.JButton delbtn;
    private javax.swing.JTextField ffld;
    private javax.swing.JTextField idfld;
    private javax.swing.JLabel idlbl;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable21;
    private javax.swing.JTextField mfld;
    private javax.swing.JTextField namefld;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("dgre.png")));
         //To change body of generated methods, choose Tools | Templates.
    }

    private void showTableData() {
        
        //To change body of generated methods, choose Tools | Templates.
        
        try{
         conn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb","root","");
         String sql = "SELECT ID, Name, FathersName, MothersName, Age, Address, Contact FROM studentinfo";
         pst = conn.prepareStatement(sql);
         rs=pst.executeQuery();
         jTable21.setModel(DbUtils.resultSetToTableModel(rs));
 }
     catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
         
     }
        
    }
}
